// Generated by CoffeeScript 1.7.1
(function() {
  angular.module('directiveSeed', []).controller('controller', [
    '$scope', function($scope) {
      return $scope.awesome = '... wait for it ... awesome';
    }
  ]).directive('directiveSeed', function() {
    return {
      restrict: 'E',
      controller: 'controller',
      scope: {},
      templateUrl: 'directive-seed.html'
    };
  });

}).call(this);

//# sourceMappingURL=directive-seed.map
